name: automated tests
on:
  push:
    branches: [ main]
jobs:
  playwright:
    name: 'Playwright automated Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.53.0-noble
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run your tests
        run: |
          playwright install --with-deps
          python -m pytest -m training
